name: Nintendo Switch CI

on: [push, pull_request]

jobs:
  build:
    name: Switch ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    strategy:
      matrix:
        config:
          - {name: standalone, destDir: switch}
          - {name: libretro, cmakeArgs: -DLIBRETRO=ON}

    steps:
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get -y install awscli ccache

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Mark git repository as safe
        run: git config --global --add safe.directory $PWD

      - uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-switch-${{ matrix.config.name }}-${{ github.sha }}
          restore-keys: ccache-switch-${{ matrix.config.name }}-

      - name: CMake
        run: |
          $DEVKITPRO/portlibs/switch/bin/aarch64-none-elf-cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=artifact -G Ninja ${{ matrix.config.cmakeArgs }}
          cmake --build build --config Release --target install

      - uses: actions/upload-artifact@v4
        with:
          name: flycast-switch-${{ matrix.config.name }}
          path: artifact/bin

      - name: Package app
        run: zip -m artifact/bin/flycast.nro.zip artifact/bin/flycast.nro
        if: hashFiles('artifact/bin/flycast.nro') != ''

      - name: Upload to S3
        run: |
          aws configure set aws_access_key_id 9d1dcc5e9a6445c9a7380c7d3e98ffb7
          aws configure set aws_secret_access_key ${{ secrets.OVH_SECRET_KEY }}
          aws s3 --endpoint https://s3.gra.io.cloud.ovh.net/ cp artifact/bin s3://flycast-builds/${{ matrix.config.destDir }}/${GITHUB_REF#refs/}-$GITHUB_SHA --acl public-read --follow-symlinks --recursive
        if: github.repository == 'flyinghead/flycast' && github.event_name == 'push' && matrix.config.destDir != ''
