name: Windows UWP CI

on: [push, pull_request]

jobs:
  build:
    name: UWP
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_NAME=WindowsStore -DCMAKE_SYSTEM_VERSION=10.0.22000.0
          cmake --build build --config Release -- /m
        shell: cmd

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Package app
        run: |
          mkdir build\artifact
          cd build\AppPackages\flycast\flycast_*_x64_Test
          mkdir tmp
          ren *.msix flycast.msix
          makeappx.exe unpack /p .\flycast.msix /d tmp
          copy ..\..\..\Release\*.dll tmp
          makeappx pack /d tmp /p ..\..\..\artifact\flycast.appx

      - name: Sign app
        run: signtool sign /f shell\uwp\sign_cert.pfx /p '${{ secrets.SIGN_CERT_PWD }}' /v /fd SHA256 build\artifact\flycast.appx
        if: github.repository == 'flyinghead/flycast' && github.event_name == 'push'

      - uses: actions/upload-artifact@v4
        with:
          name: flycast-uwp
          path: build/artifact

      - name: Upload to S3
        run: |
          aws configure set aws_access_key_id 9d1dcc5e9a6445c9a7380c7d3e98ffb7
          aws configure set aws_secret_access_key ${{ secrets.OVH_SECRET_KEY }}
          aws s3 --endpoint https://s3.gra.io.cloud.ovh.net/ sync build/artifact s3://flycast-builds/xbox/${GITHUB_REF#refs/}-$GITHUB_SHA --acl public-read --follow-symlinks
        shell: bash
        if: github.repository == 'flyinghead/flycast' && github.event_name == 'push'
